# Generated by Django 4.1.3 on 2022-11-27 06:28

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address_1",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="location",
            name="address_2",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=localflavor.us.models.USStateField(default="NY", max_length=2),
        ),
        migrations.AddField(
            model_name="location",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
