# Generated by Django 4.1.3 on 2022-11-27 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_location_address_1_location_address_2_location_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.location",
            ),
        ),
    ]
